stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "registry.gitlab.com/your-namespace/your-project:latest"
  DOCKER_HOST: "tcp://docker:2375"

before_script:
  - echo "Démarrage du pipeline CI/CD"
a
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - main

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Lancement des tests..."
    - docker run --rm $IMAGE_NAME pytest  # Modifier selon les tests utilisés
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
  script:
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' > id_rsa
    - chmod 600 id_rsa
    - ssh -o StrictHostKeyChecking=no -i id_rsa user@your-server "cd /path/to/project && docker-compose pull && docker-compose up -d --force-recreate"
  only:
    - main
