services:

  dev-toolbox:
    container_name: dev-toolbox
    image: dev-toolbox:latest
    volumes:
      - ./api:/home/back
    command: bash -c "cd /home/back/ && mvn clean install"

  frontend:
    container_name: frontend-nginx
    build: ./frontend
    ports:
      - "8081:80"
    networks:
      - api-net
    depends_on:
      - api